config/routes.rb
RdsLeads::Application.routes.draw do
  resources :leads

  root :to => 'leads#index'

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  
  include CrmCallback
  
  attr_accessible :company, :email, :first_name, :job_title, :last_name, :phone, :website
  
  validates_presence_of :company, :email, :last_name
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  
  def index
    @leads = Lead.all
  end

  def show
    @lead = Lead.find(params[:id])
  end

  def new
    @lead = Lead.new
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def create
    @lead = Lead.new(params[:lead])

    if @lead.save
      redirect_to @lead, notice: 'Lead was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @lead = Lead.find(params[:id])

    if @lead.update_attributes(params[:lead])
      redirect_to @lead, notice: 'Lead was successfully updated.' 
    else
      render action: "edit" 
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    redirect_to leads_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RdsLeads</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br />
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<h1>Listing leads</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Company</th>
    <th>Email</th>
    <th>Job title</th>
    <th>Phone</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leads.each do |lead| %>
  <tr>
    <td><%= lead.first_name %></td>
    <td><%= lead.last_name %></td>
    <td><%= lead.company %></td>
    <td><%= lead.email %></td>
    <td><%= lead.job_title %></td>
    <td><%= lead.phone %></td>
    <td><%= lead.website %></td>
    <td><%= link_to 'Show', lead %></td>
    <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
    <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @lead.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @lead.last_name %>
</p>

<p>
  <b>Company:</b>
  <%= @lead.company %>
</p>

<p>
  <b>Email:</b>
  <%= @lead.email %>
</p>

<p>
  <b>Job title:</b>
  <%= @lead.job_title %>
</p>

<p>
  <b>Phone:</b>
  <%= @lead.phone %>
</p>

<p>
  <b>Website:</b>
  <%= @lead.website %>
</p>


<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>